### ISSUE TITLE
Other OCR language support doesn't work?

### ISSUE THREAD

**Issue by hereinmyhead** [linuxserver/docker-paperless-ng#10]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
I'm using a Synology NAS Plus-series with Docker. 

Use other OCR languages doesn't seem to work. 

In the Docs for Paperless-ng (https://paperless-ng.readthedocs.io/en/latest/configuration.html?highlight=docker%20ocr#docker-specific-options) there is instructions for installation of more OCR language support. I have followed the guide and used this config:

`PAPERLESS_OCR_LANGUAGES=swe`
`PAPERLESS_OCR_LANGUAGE=swe`

The expected behavior is that OCR for Swedish installs and get used.

## Current Behavior
I get error in my logs. The application doesn't consume any documents.

## Steps to Reproduce

Use this variables in config enviroment:
`PAPERLESS_OCR_LANGUAGES=swe`
`PAPERLESS_OCR_LANGUAGE=swe`

## Environment
**OS: DSM 7**
**CPU architecture: arm64
**How docker service was installed:**
Via Synology Package Center - Docker

## Command used to create docker container (run/create/compose/screenshot)

docker run -d --name=paperless-ng \
-p 8931:8000 \
-e PUID=XXXX \
-e PGID=XXXX \
-e TZ=Europe/Stockholm \
-v /volume1/docker/paperless/config:/config \
-v /volume1/docker/paperless/data:/data \
--restart always \
ghcr.io/linuxserver/paperless-ng

## Docker logs

`2021-09-21 13:24:47,stderr,[uwsgi-daemons] respawning "/usr/bin/python3 /app/paperless/src/manage.py document_consumer" (uid: 1026 gid: 100)
2021-09-21 13:24:47,stderr,[uwsgi-daemons] respawning "/usr/bin/python3 /app/paperless/src/manage.py qcluster" (uid: 1026 gid: 100)
2021-09-21 13:24:46,stderr,[uwsgi-daemons] throttling "/usr/bin/python3 /app/paperless/src/manage.py document_consumer" for 1 seconds
2021-09-21 13:24:46,stderr,[uwsgi-daemons] throttling "/usr/bin/python3 /app/paperless/src/manage.py qcluster" for 1 seconds
2021-09-21 13:24:45,stderr,?: The selected ocr language swe is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.
2021-09-21 13:24:45,stderr,ERRORS:
2021-09-21 13:24:45,stderr,
2021-09-21 13:24:45,stderr,SystemCheckError: System check identified some issues:
2021-09-21 13:24:45,stderr,?: The selected ocr language swe is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.
2021-09-21 13:24:45,stderr,ERRORS:
2021-09-21 13:24:45,stderr,
2021-09-21 13:24:45,stderr,SystemCheckError: System check identified some issues:
2021-09-21 13:24:44,stderr,[uwsgi-daemons] spawning "/usr/bin/python3 /app/paperless/src/manage.py qcluster" (uid: 1026 gid: 100)
2021-09-21 13:24:44,stderr,[uwsgi-daemons] spawning "/usr/bin/python3 /app/paperless/src/manage.py document_consumer" (uid: 1026 gid: 100)
2021-09-21 13:24:44,stderr,"spawned uWSGI worker 1 (pid: 1196, cores: 1)
2021-09-21 13:24:43,stdout,"0 static files copied to '/app/paperless/static', 409 unmodified.
2021-09-21 13:24:42,stderr,*** Operational MODE: single process ***
2021-09-21 13:24:42,stderr,mapped 145840 bytes (142 KB) for 1 cores
2021-09-21 13:24:42,stderr,your mercy for graceful operations on workers is 60 seconds
2021-09-21 13:24:42,stderr,your server socket listen backlog is limited to 100 connections
2021-09-21 13:24:42,stderr,python threads support enabled
2021-09-21 13:24:42,stderr,Python main interpreter initialized at 0x56000b0abf20
2021-09-21 13:24:42,stderr,"Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
2021-09-21 13:24:39,stderr,...brutally killing workers...
2021-09-21 13:24:39,stderr,[uwsgi-daemons] stopping daemon (pid: 1146): /usr/bin/python3 /app/paperless/src/manage.py qcluster
2021-09-21 13:24:39,stderr,[uwsgi-daemons] stopping daemon (pid: 1163): /usr/bin/python3 /app/paperless/src/manage.py document_consumer
2021-09-21 13:24:39,stderr,[uwsgi-daemons] stopping daemon (pid: 1164): /usr/bin/python3 /app/paperless/src/manage.py qcluster
2021-09-21 13:24:38,stdout,"320:M 21 Sep 2021 15:24:38.021 # Redis is now ready to exit, bye bye...
2021-09-21 13:24:37,stderr,...brutally killing workers...
2021-09-21 13:24:37,stderr,[uwsgi-daemons] stopping daemon (pid: 1146): /usr/bin/python3 /app/paperless/src/manage.py qcluster
2021-09-21 13:24:37,stderr,[uwsgi-daemons] stopping daemon (pid: 1145): /usr/bin/python3 /app/paperless/src/manage.py document_consumer
2021-09-21 13:24:37,stderr,[uwsgi-daemons] stopping daemon (pid: 1163): /usr/bin/python3 /app/paperless/src/manage.py document_consumer
2021-09-21 13:24:37,stdout,320:signal-handler (1632230677) Received SIGTERM scheduling shutdown...
2021-09-21 13:24:32,stderr,[uwsgi-daemons] throttling "/usr/bin/python3 /app/paperless/src/manage.py document_consumer" for 43 seconds
2021-09-21 13:24:32,stderr,[uwsgi-daemons] throttling "/usr/bin/python3 /app/paperless/src/manage.py qcluster" for 43 seconds
2021-09-21 13:24:31,stderr,?: The selected ocr language swe is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.
2021-09-21 13:24:31,stderr,ERRORS:
2021-09-21 13:24:31,stderr,
2021-09-21 13:24:31,stderr,SystemCheckError: System check identified some issues:
2021-09-21 13:24:31,stderr,?: The selected ocr language swe is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.`

**Comment by aptalca** [comment]
You need this mod: https://github.com/linuxserver/docker-mods/tree/papermerge-multilangocr

**Comment by Roxedus** [comment]
We do not currently support the declaration of additional ocr languages the way the official container do, you can use the papermerge ocr mod, as discussed in #4

**Comment by hereinmyhead** [comment]
Thank you and I got it to work! Amazing support! :)

**Comment by hereinmyhead** [comment]
Oh no, I thought it was working but I was wrong. I tried with a PDF that already had OCR data.

I am using this enviorment variables:

`DOCKER_MODS=linuxserver/mods:papermerge-multilangocr`
`OCRLANG=swe`
`PAPERLESS_OCR_MODE=swe`

When I consume a PDF for OCR processing (without OCR data) I get this error message:

_[2021-09-21 16:58:52,976] [INFO] [paperless.consumer] Consuming XXXXXXXXXXX.pdf
[2021-09-21 16:58:52,979] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2021-09-21 16:58:53,053] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2021-09-21 16:58:53,057] [DEBUG] [paperless.consumer] Parsing 20210818.Burlovs.Bostader.Uppsägningsblankett.Ifylld.pdf...
[2021-09-21 16:58:53,768] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /tmp/paperless/paperless-upload-w89ned7x
[2021-09-21 16:58:54,592] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-u_d6s6os
[2021-09-21 16:58:54,596] [ERROR] [paperless.consumer] Error while consuming document 20210818.Burlovs.Bostader.Uppsägningsblankett.Ifylld.pdf: Invalid ocr mode: swe
Traceback (most recent call last):
  File "/app/paperless/src/documents/consumer.py", line 248, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/app/paperless/src/paperless_tesseract/parsers.py", line 236, in parse
    args = self.construct_ocrmypdf_parameters(
  File "/app/paperless/src/paperless_tesseract/parsers.py", line 158, in construct_ocrmypdf_parameters
    raise ParseError(
documents.parsers.ParseError: Invalid ocr mode: swe_

Have I done something wrong? Thank you!
