### ISSUE TITLE
specifying external redis does not work

### ISSUE THREAD

**Issue by chasebolt** [linuxserver/docker-paperless-ng#18]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Setting `REDIS_URL=redis://myredis` should connect to my external redis instance and boot the app successfully.

## Current Behavior
The applications try to connect to `redis://localhost:6379` and fail.

## Steps to Reproduce

```sh
docker network create redis-test
docker run --name myredis --net redis-test -d redis
docker run -it --rm -e 'REDIS_URL=redis://myredis' --net redis-test linuxserver/paperless-ng
``` 

## Environment
**OS:** flatcar linux
**CPU architecture:** x86_64
**How docker service was installed:** native

## Docker logs

```
19:46:19 [Q] ERROR Can not connect to Redis server.
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.8/dist-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/usr/local/lib/python3.8/dist-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django_q/cluster.py", line 168, in __init__
    self.start()
  File "/usr/local/lib/python3.8/dist-packages/django_q/cluster.py", line 171, in start
    self.broker.ping()
  File "/usr/local/lib/python3.8/dist-packages/django_q/brokers/redis_broker.py", line 39, in ping
    raise e
  File "/usr/local/lib/python3.8/dist-packages/django_q/brokers/redis_broker.py", line 36, in ping
    return self.connection.ping()
  File "/usr/local/lib/python3.8/dist-packages/redis/client.py", line 1378, in ping
    return self.execute_command('PING')
  File "/usr/local/lib/python3.8/dist-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.8/dist-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.8/dist-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.
```

**Comment by arturoovf** [comment]
same issue

**Comment by hadjilucasL** [comment]
The correct variable name according to the [paperless-ng documentation](https://paperless-ng.readthedocs.io/en/latest/configuration.html#required-services) is `PAPERLESS_REDIS` so set that instead.

**Comment by chasebolt** [comment]
> The correct variable name according to the [paperless-ng documentation](https://paperless-ng.readthedocs.io/en/latest/configuration.html#required-services) is `PAPERLESS_REDIS` so set that instead.

if you look at the code for this docker container, that won't work.

**Comment by chasebolt** [comment]
still an issue
